# ---- p10k instant prompt ---- #

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# ---- oh-my-zsh + theme ---- #

export ZSH="$HOME/.oh-my-zsh"
if [[ -f "$ZSH/oh-my-zsh.sh" ]]; then
  ZSH_THEME="powerlevel10k/powerlevel10k"
  plugins=(
    kubectl
    git
    zsh-autosuggestions
    zsh-syntax-highlighting
    web-search
  )
  source "$ZSH/oh-my-zsh.sh"
fi

# ---- p10k theme config (generated by `p10k configure`) ---- #

[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh


# ----------------- #
# ---- Aliases ---- #
# ----------------- #

# ---- Lazy Tools ----#

alias lg='lazygit'
alias lzd='lazydocker'

# ---- NeoVim ---- #

alias n='nvim'
alias nv='nvim'
alias vim='nvim'

# ---- evals ---- #

if command -v uv >/dev/null 2>&1; then
  eval "$(uv generate-shell-completion zsh)"
fi

if command -v zoxide >/dev/null 2>&1; then
  eval "$(zoxide init zsh)"
fi

