# ---- p10k instant prompt: keep this at the very top ---- #
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# ---- oh-my-zsh + theme ---- #
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"
plugins=(git zsh-autosuggestions zsh-syntax-highlighting web-search)

source "$ZSH/oh-my-zsh.sh"

# ---- p10k theme config (generated by `p10k configure`) ---- #
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh

# ---- Shell completions / integrations ---- #
# Kiro terminal integration (keep if you use Kiro)
[[ "$TERM_PROGRAM" == "kiro" ]] && . "$(kiro --locate-shell-integration-path zsh)"

# uv completions
eval "$(uv generate-shell-completion zsh)"

# ---- Aliases & functions you actually use ---- #
alias lg='lazygit'
alias lzd='lazydocker'
alias nv='nvim'
# this is a test
