# $HOME/.config/herdr/config.toml

# Run `herdr --default-config` to view all available options and their defaults.

onboarding = false

[theme]
name = "tokyo-night"

[keys]
prefix = "ctrl+alt+cmd+shift+space"

# Zoom
zoom = ["ctrl+alt+cmd+shift+enter", "prefix+z"]

# Pane Navigation
focus_pane_left = ["ctrl+alt+cmd+shift+h", "prefix+h"]
focus_pane_down = ["ctrl+alt+cmd+shift+j", "prefix+j"]
focus_pane_up = ["ctrl+alt+cmd+shift+k", "prefix+k"]
focus_pane_right = ["ctrl+alt+cmd+shift+l", "prefix+l"]

# Split Panes
split_vertical = ["alt+d", "prefix+v"]
split_horizontal = ["alt+shift+d", "prefix+minus"]

# Tab Navigation
previous_tab = ["ctrl+alt+h", "prefix+p"]
next_tab = ["ctrl+alt+l", "prefix+n"]

# Workspace Navigation
previous_workspace = "ctrl+alt+k"
next_workspace = "ctrl+alt+j"
switch_workspace = "ctrl+alt+1..9"

# Agent Navigation
previous_agent = "ctrl+alt+shift+k"
next_agent = "ctrl+alt+shift+j"
focus_agent = "ctrl+alt+shift+1..9"
