# $HOME/.config/herdr/config.toml

# Run `herdr --default-config` to view all available options and their defaults.

onboarding = false

[theme]
name = "tokyo-night"

[keys]
prefix = "ctrl+alt+cmd+shift+space"

# Pane Navigation
focus_pane_left = "ctrl+alt+cmd+shift+h"
focus_pane_down = "ctrl+alt+cmd+shift+j"
focus_pane_up = "ctrl+alt+cmd+shift+k"
focus_pane_right = "ctrl+alt+cmd+shift+l"

# Split Panes
split_vertical = "alt+d"
split_horizontal = "alt+shift+d"

# Tab Navigation
previous_tab = "ctrl+alt+h"
next_tab = "ctrl+alt+l"

# Workspace Navigation
previous_workspace = "ctrl+alt+k"
next_workspace = "ctrl+alt+j"
switch_workspace = "ctrl+alt+1..9"

# Agent Navigation
previous_agent = "ctrl+alt+shift+k"
next_agent = "ctrl+alt+shift+j"
focus_agent = "ctrl+alt+shift+1..9"
