# ---- p10k instant prompt ---- #
#
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# ---- p10k theme config (generated by `p10k configure`) ---- #

[[ -r "$HOME/.p10k.zsh" ]] && source "$HOME/.p10k.zsh"

# ---- oh-my-zsh + theme ---- #

export ZSH="$HOME/.oh-my-zsh"
if [[ -f "$ZSH/oh-my-zsh.sh" ]]; then
  ZSH_THEME="powerlevel10k/powerlevel10k"
  plugins=(
    aws
    git
    helm
    history
    k9s
    kubectl
    terraform
    uv
    web-search
    zsh-autosuggestions
    zsh-syntax-highlighting
  )
  source "$ZSH/oh-my-zsh.sh"
fi

# ---- Bind to current TTY for commit/tag signing prompts ---- #
export GPG_TTY="$(tty)"


# ---- private zshrc ---- #

[[ -r "$HOME/.zshrc.private" ]] && source "$HOME/.zshrc.private"

# --- Docker Desktop --- #

[[ -r "$HOME/.docker/init-zsh.sh" ]] && source "$HOME/.docker/init-zsh.sh"

# ---------------------- #
# ---- Autocomplete ---- #
# ---------------------- #

# --- terraform autocomplete --- #

if command -v terraform >/dev/null 2>&1; then
  autoload -U +X bashcompinit && bashcompinit
  complete -o nospace -C "$(command -v terraform)" terraform 2>/dev/null
fi

# ----------------- #
# ---- Aliases ---- #
# ----------------- #

# ---- Lazy Tools ----#

alias lg='lazygit'
alias lzd='lazydocker'

# ---- NeoVim ---- #

alias n='nvim'
alias nv='nvim'
alias vim='nvim'

# --- edit .z files --- #
alias nz='nvim ~/.zshrc'
alias sz='source ~/.zshrc'
alias nzp='nvim ~/.zprofile'
alias szp='source ~/.zprofile'

# ------------------------------------------------ #
#                  shell                     #
# ------------------------------------------------ #

alias e='exit'
alias q='exit'

# ---- AWS: SSO login + set shell context ---- #
al() {
  if [[ -z "$1" ]]; then
    echo "Usage: al <profile>"
    return 1
  fi

  local profile="$1"

  # Prefer OMZ aws plugin helper if present
  if whence -w asp >/dev/null 2>&1; then
    asp "$profile" login || return 1
  else
    aws sso login --profile "$profile" || return 1
    export AWS_PROFILE="$profile"
    export AWS_DEFAULT_PROFILE="$profile"
  fi

  # Set region if not already set (uses profile config)
  if [[ -z "${AWS_REGION:-}" && -z "${AWS_DEFAULT_REGION:-}" ]]; then
    local region
    region="$(aws configure get region --profile "$profile" 2>/dev/null)"
    [[ -n "$region" ]] && export AWS_REGION="$region" AWS_DEFAULT_REGION="$region"
  fi

  export AWS_ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text 2>/dev/null)"
  local arn
  arn="$(aws sts get-caller-identity --query Arn --output text 2>/dev/null)"

  echo "Logged in. profile='$profile' account='${AWS_ACCOUNT_ID:-?}' region='${AWS_REGION:-${AWS_DEFAULT_REGION:-?}}'"
  [[ -n "$arn" ]] && echo "Caller: $arn"
}

# ---- evals ---- #

if command -v uv >/dev/null 2>&1; then
  eval "$(uv generate-shell-completion zsh)"
fi

if command -v zoxide >/dev/null 2>&1; then
  eval "$(zoxide init zsh)"
fi

